### ISSUE TITLE
Basic example doesn't work

### ISSUE THREAD

**Issue by Ryangeorge-ctrl** [chemicaljs/basic-example#1]
![{E3CD2909-6603-46CF-8A9E-F6FA4F6FFBBF}](https://github.com/user-attachments/assets/5dbe06a0-50de-45d5-a4b9-930234603dda)
Bing looks like this on the Basic Example.

**Comment by Nebelung-Dev** [comment]
its outdated install the latest version with `npm i chemicaljs@latest`

**Comment by Nebelung-Dev** [comment]
everything should be up to date now. if its still not working try updating nodejs
